config/routes.rb
Rails.application.routes.draw do

  get 'ask', to: 'coaching#ask'
  
  get 'answer', to: 'coaching#answer'

  root to: 'coaching#ask'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/coaching_controller.rb
class CoachingController < ApplicationController
  def ask
  end

  def answer
  	@ask = params[:query]
  	@answer = coaching
  end

private 

  def coaching
  	if @ask.include? "?" 
	   "Silly question, get dressed and go to work!"
	 elsif @ask == "I am going to work right now."
	  return "Good son !"
	 else
	   "I don't care, get dressed and go to work!"
	 end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaching_helper.rb
module CoachingHelper
end

app/views/coaching/answer.html.erb
<div class="flex container">
  <div class="wrapper">


    <div class="user display-text text-center">
      <h1><%= @ask%></h1>
      <h2>- You</h2>
    </div>

	<div class="coach display-text text-center">
	    <h1><%= @answer %> </h1>
	    <h2>- Your coach</h2>
    </div>
  </div>
</div>


<div class="link text-center"><%= link_to "Ask a new question to my coach", ask_path%></div> 

app/views/coaching/ask.html.erb
<!-- <div class="flex container">
  <div class="wrapper">
    <div class="coach display-text text-center">
      <h1>What's up bro ?</h1>
      <h2>- Your coach</h2>
    </div>
  </div>
</div> -->

<form action="/answer">
  <label for="question">Speak to your coach</label>
  <input type="text" id="question" name="query" placeholder="what time is it coach?">
  <input type="submit" value="Go on!">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>